services:
  - type: web
    name: emirates-app
    env: php
    buildCommand: >
      composer install --no-dev --optimize-autoloader &&
      npm install &&
      npm run build &&
      php artisan migrate --force &&
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    autoDeploy: true
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:REPLACE_THIS_WITH_REAL_KEY
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
        
